### ISSUE TITLE
Results not appearing from 1password (and how to get back to terminal)

### ISSUE THREAD

**Issue by pnigrini** [alfredapp/1password-workflow#22]
Hello,

I believe I followed the install properly.

I received a notice saying that the database was being built and closed the terminal window.

I have not at any time seen results in Alfred.

Thanks for your help.

**Comment by vitorgalvao** [comment]
Hello. Please don’t skip [the template](https://github.com/alfredapp/1password-workflow/issues/new?assignees=&labels=&template=bug_report.yml). I cannot help you unless you fill it out, because without it I have no context over your setup or what might be wrong.

It’s hard to go back to it now, so please open a new issue.

**Comment by vitorgalvao** [comment]
If you want to reset the Workflow beforehand, run `:1pextras` and pick `Reset accounts`.

**Comment by pnigrini** [comment]
Thanks for your help.


I found the error on my part.


One quick confusing part is that after I entered the incorrect password (Like I said, totally my fault)

The terminal reported the error (and I missed that, again my fault)

And then it said. . . 


> Updating items list. It will take a few seconds to complete.
> You may close the terminal at any time.
> .%                                        


Which is the part that I read.


Thanks again for your help.




________________________________
Peter Nigrini
Theatre Designer

**Comment by vitorgalvao** [comment]
Glad it’s sorted. Have a nice weekend!
