### ISSUE TITLE
Regression: Cannot "fuzzy search" 

### ISSUE THREAD

**Issue by cmer** [alfredapp/1password-workflow#25]
### Workflow version
2022.10

### Alfred version
4.6.5

### macOS version
12.3.1

### Architecture
arm64

### Workflow environment variables
Dict {
    auto_refresh = 1
    logins_only = 0
    hostnames_only = 1
}

### 1Password version
8.7.0

### op version
In Workflow: 2.1.0
In /usr/local: 2.0.2

### Biometric unlock
NOT enabled

### Custom terminal feature
Enabled

### Launchd job
Loaded: -	0	com.alfredapp.1password
Installed

### Debugger output

```codeblock
N/A
```

### Terminal output

```terminal_text
N/A
```

### More details

I have many similar entries in 1Password and am used to "fuzzy searching" for them, just like with everything in Alfred. However, this doesn't work with the new 1P workflow.

For example, let's say I have the following login entries in 1P:

`Bank of America (John)`
`Bank of America (Business)`

I expect to be able to type `1p bank bus` to find `Bank of America (Business)`, or `1p bank john` to find `Bank of America (John)`, but it does not work. Search will only find exact matches. This is not how Alfred typically works and is not how the old workflow worked.

**Comment by vitorgalvao** [comment]
> type `1p bank bus` to find `Bank of America (Business)`

Due to how filtering works, that is not possible without complicating the Workflow (and likely making it slower). However, it is possible to type `1p bank (bus` to find `Bank of America (Business)`. Note how the difference is that because the parenthesis is part of the word, it has to be included.

That change will be out in the next release (which will have other changes), but you can use it right now [with this version](https://github.com/alfredapp/1password-workflow/files/8662335/1Password.alfredworkflow.zip).

**Comment by vitorgalvao** [comment]
In Alfred 5, [currently in Early Access](https://www.alfredapp.com/alfred-5-whats-new/), a new filtering mode will accommodate the case better, ignoring the parenthesis.
