### ISSUE TITLE
Unable to open and parse 1password database

### ISSUE THREAD

**Issue by msudgh** [alfredapp/1password-workflow#8]
Hi @vitorgalvao, I tried to use new workflow but encountered to this error. Any idea?
I should note that 1password works fine on own app

![SCR-20220427-usa](https://user-images.githubusercontent.com/11756815/165587238-16d27fe7-e539-4ec0-bdd4-d060ff3359cd.png)

**Comment by vitorgalvao** [comment]
Hello. For future issues, please don’t skip the bug report template. It has information that I need. When it’s not followed, we waste our time in back and forth for information which was already requested.

You don’t need to obfuscate the UID in the 1Password path, because it’s hardcoded. Can you check if that directory exists, or one with a similar path but a different UID?

Also, what’s the exact version of your 1Password app?

**Comment by vitorgalvao** [comment]
Importantly, the command still worked. As in, you’ll still see your items when you `1p`. What failed was something different.

**Comment by msudgh** [comment]
My bad. For sure, I'll respect the community guidelines.

The issue is that I could not find a directory for 1password(the same path, with a different id) and there was no directory for 1password in `~/Library/Group Containers`

I have 1Password 7.9.4 (70904002) installed

Could it be a compatibility issue? 7 or 8?

**Comment by msudgh** [comment]
I just locked laptop and backed to respond your comment and found alfred now load 1Password items. works fine

**Comment by vitorgalvao** [comment]
> I have 1Password 7.9.4 (70904002) installed
>
> Could it be a compatibility issue? 7 or 8?

As per the first line of the instructions:

> This Workflow is for 1Password 8. For older versions, see Alfred Preferences → Features → 1Password.
