### ISSUE TITLE
Copy an item into clipboard

### ISSUE THREAD

**Issue by msudgh** [alfredapp/1password-workflow#9]
Is it possible to copy an item into clipboard? 
I'm not sure but does 1password allow to access password from side of third-party?

Also, it would be great to have this feature like nested actions

```
1. Search by 1p
2. Open action and continue in alfred
3. Copy one of the 1password item labels as nested actions (website/password/...)
```

Let me know if its not enough clear

**Comment by vitorgalvao** [comment]
It is possible, but it wouldn’t be a good experience. When the item information is requested, a handful of information is retrieved for all items. To get more (not that much more in most cases), it would require another request for each individual item, which would considerably slow down the retrieval.

We could copy the website, yes, but that doesn’t seem terribly useful considering the extra complication to the interaction.

If it turns out more people want that specifically, I’ll revisit it.

Thank you for the feature request.

**Comment by vitorgalvao** [comment]
Recent improvements now make this viable with security and convenience. Version [2022.17](https://github.com/alfredapp/1password-workflow/releases/tag/2022.17) is out and available for testing. [More details on the forum post](https://www.alfredforum.com/topic/18275-1password-—-search-and-open-1password-items/page/6/#comment-98858).
